server:
  port: 8081

spring:
  application:
    name: yeb-server

  datasource:
    url: jdbc:mysql://localhost:3306/yeb?characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    #redis相关配置
  redis:
    host: '182.92.156.43'
    port: 6379
    password: 'znclittlefriend111'
    client-name: 'jedis'
    #配置超时时间
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数
        max-active: 1024
        #最长等待时间
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5
  main:
    allow-bean-definition-overriding: true

  #文件上传
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      #单个文件大小
      max-request-size: 100MB
      #多个文件总数据大小
      max-file-size: 100MB

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.chen.server.pojo
  configuration:
    # 关闭驼峰命名
    map-underscore-to-camel-case: false
    #终端打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


jwt:
  tokenHeader: Authorization
  secret: yeb-secret
  expiration: 604800
  tokenHead: Bearer

